spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/stu_management?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true

  checkResultPath: C:/Users/wdy/Desktop/submit/result/
  uploadPath: C:/Users/wdy/Desktop/submit/
  proxyUrl: http://piping.mogumiao.com/proxy/api/get_ip_bs?appKey=e9d00484240d4d2c9a3f6d2029aadab9&count=1&expiryDate=0&format=1&newLine=2


  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB


server:
  port: 8000


#\u903B\u8F91\u5220\u9664\u5168\u5C40\u914D\u7F6E
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isdel
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



